### PR TITLE
fix: fix indefinite spinner for terminal single-trial experiments

### LINKED ISSUE #2764: terminal single trial experiments with no trial show a waiting spinner
when:
- terminal experiment state
- single trial experiment
- we have checked the trial list and its empty

then:
- no trials

### PR DESCRIPTION
**Pull request by hamidzr**
## Description

when we know the experiment is terminated:
- make sure the loading spinner goes away 
- we stop polling for the list of trials

## Commentary (optional)

fixes #2764 

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

File: webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx [hunk 1]
```diff
@@ -125,21 +130,22 @@ const ExperimentSingleTrialTabs: React.FC<Props> = (
   }, [ trialDetails, stopPolling ]);
 
   useEffect(() => {
-    if (trialId != null) return;
-    return () => stopPollingFirstTrialId();
-  }, [ trialId, stopPollingFirstTrialId ]);
+    if (trialId === undefined && wontHaveTrials === false) return;
```
Comment (EmilyBonar) [inline webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx:133]: fix: shouldn't this be `trialId !== undefined && wontHaveTrials === false`? Or maybe more simply `trialId && !wontHaveTrials`.

File: webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx [hunk 2]
```diff
@@ -77,12 +78,16 @@ const ExperimentSingleTrialTabs: React.FC<Props> = (
 
   const fetchFirstTrialId = useCallback(async () => {
     try {
+      // make sure the experiment is in terminal state before the request is made.
+      const isTerminalExp = terminalRunStates.has(experiment.state);
```
Comment (EmilyBonar) [inline webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx:82]: question: if `isTerminalExp` is true, why not just immediately set `wontHaveTrials` to true and return?

**Review by EmilyBonar — APPROVED** [review]
Otherwise looks good

File: webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx (hunk 2 above)
Comment (hamidzr) [reply webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx:82]: to make sure we at least check once. it could be that the experiment is in a terminal state but has trials.

File: webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx (hunk 1 above)
Comment (hamidzr) [reply webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx:133]: aah I was a bit confused around that check 🤔 let me see

Comment (hamidzr) [reply webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx]: does [this](https://github.com/determined-ai/determined/pull/2772/commits/71483c8e975eba610eaa7f8d5e8d76f92aa9b2f9) make sense?

File: webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx [hunk 3]
```diff
@@ -77,12 +78,16 @@ const ExperimentSingleTrialTabs: React.FC<Props> = (
...
       const expTrials = await getExpTrials(
         { id: experiment.id, limit: 2 },
         { signal: canceler.signal },
       );
       if (expTrials.trials[0]) {
         setFirstTrialId(expTrials.trials[0].id);
+      } else if (isTerminalExp) {
```
Comment (hkang1) [inline webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx:89]: **question:** should this also check to see if `experiment.state` is `PAUSED`?

Comment (hkang1) [reply webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx:89]: discussed async, we don't want the polling to stop if experiment is paused in the case the experiment is resumed externally (outside of this page).

**Review by hkang1 — APPROVED** [review]
LGTM, it's working great. Thanks for fixing this!
