### PR TITLE
test: fix waiting on dropdown animation

### LINKED ISSUE #2872: tests: fix tasks batch action test flake
two instances
https://app.circleci.com/pipelines/github/determined-ai/determined/14918/workflows/cbe93d30-7177-443a-a9c7-eae8e80203e2/jobs/448031
https://app.circleci.com/pipelines/github/determined-ai/determined/14916/workflows/1688dda3-8f95-4fba-9a7c-7a6717d377b5/jobs/447985

circleci stats show a 16%  decrease in pass rate for it to 76%

### PR DESCRIPTION
**Pull request by hamidzr**
## Commentary (optional)

fixes #2872

## Checklist

- [x] User-facing API changes need the "User-facing API Change" label.
- [x] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](../docs/release-notes/README.md) for details.
- [x] Licenses should be included for new code which was copied and/or modified from any external code.

[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234

### CODE REVIEW

File: webui/tests/tests/StepImplementation.ts [hunk 1]
```diff
@@ -466,4 +471,22 @@ export default class StepImplementation {
       return logs.length > 0;
     });
   }
+
+  /* Dev */
+  @Step('dev')
+  public async dev() {
+    await this.navigateToTaskList();
```
Comment (hamidzr) [inline webui/tests/tests/StepImplementation.ts:478]: this is some of the attempts I made trying to understand taiko and fix this issue.  I probably should take it out but leave a single command in. or maybe import the contentsof this function from a gitignored file 🤔

Comment (EmilyBonar) [reply webui/tests/tests/StepImplementation.ts:478]: Yeah, removing all but a single command sounds good.

**Review by EmilyBonar — APPROVED** [review]
LGTM!
